/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./../src/runtime/vue/components/Icon.vue')['default']
    MApp: typeof import('./../src/runtime/components/App.vue')['default']
    MButton: typeof import('./../src/runtime/components/Button.vue')['default']
    MDivider: typeof import('./../src/runtime/components/Divider.vue')['default']
    MPage: typeof import('./../src/runtime/components/Page.vue')['default']
    MPageBody: typeof import('./../src/runtime/components/PageBody.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
