export default {
  arrowLeft: 'lucide:arrow-left',
  arrowRight: 'lucide:arrow-right',
  check: 'lucide:check',
  chevronDoubleLeft: 'lucide:chevrons-left',
  chevronDoubleRight: 'lucide:chevrons-right',
  chevronDown: 'lucide:chevron-down',
  chevronLeft: 'lucide:chevron-left',
  chevronRight: 'lucide:chevron-right',
  close: 'lucide:x',
  ellipsis: 'lucide:ellipsis',
  external: 'lucide:arrow-up-right',
  loading: 'lucide:loader',
  minus: 'lucide:minus',
  plus: 'lucide:plus',
  search: 'lucide:search',
  chevronUp: 'lucide:chevron-up',
  copy: 'lucide:copy',
  copyCheck: 'lucide:copy-check',
}
