name: Edge CI/CD

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  id-token: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if there are changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'packages/nuxt/src/**'
              - 'packages/nuxt/package.json'
              - 'packages/nuxt/bun.lockb'
              - 'packages/utils/src/**'
              - 'packages/utils/package.json'
              - 'packages/utils/bun.lockb'
              - 'package.json'
              - 'bun.lockb'
  ci:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.src == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: 🚀 Prepare Edge
        run: bun run dev:prepare

      - name: 💅 Lint code
        run: bun run lint

      - name: 🛠️ Build
        run: bun run build

      - uses: EndBug/version-check@v2
        id: check
        with:
          file-name: packages/nuxt/package.json
          diff-search: true

      - name: 🚀 Release Edge
        if: steps.check.outputs.changed == 'true'
        run: ./scripts/release-edge.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
